### PR TITLE
Populate the printer-uuid in the mDNS record and the attributes

### LINKED ISSUE #14: printer-uuid is missing
## Expected Behavior
 
In PWG 5100.13, `printer-uuid` is required.  The service needs to have the same UUID across reboots and it should match whatever is returned in mDNS.

## Actual Behavior

`createDefaultPrinterAttributesResponse` doesn't do anything with `printer-uuid`, so I think it's completely missing unless an attributes file that sets it is in use.

## Steps to Reproduce the Problem

1. Start the virtual printer
1. Print a job
1. Start a new print job.  Notice that the printer has a new entry and the old one is disabled

### PR DESCRIPTION
**Pull request by nmuggli**
When the server starts, it will get the printer-uuid and use that until it stops (there's no way to update this while running like updating the Printer Name from the UI).  If this is the first time the printer has started, it will generate a new UUID (assuming it's not in the config file) and save the UUID in the app preferences.  It will then use that UUID until the app is un-installed and re-installed (or the cache is cleared), at which point it will generate a new UUID.

If the printer-uuid is in the config file, it will prefer that over the generated UUID.

This also refactors PreferenceUtils.kt slightly.

Fixes #14

### CODE REVIEW

File: app/src/main/java/com/google/virtualprinter/utils/PreferenceUtils.kt [hunk 1]
```diff
@@ -70,20 +74,49 @@ object PreferenceUtils {
...
+     * Checks in this order:
+     * 1. Configuration file (installed on device)
+     * 2. SharedPreferences (persists across app restarts)
+     * 3. Generates a new UUID and saves it to SharedPreferences
      */
-    private fun getNameFromConfigFile(context: Context): String? {
+    fun getPrinterUuid(context: Context): String {
+        // 1. Check for configuration file first
+        val configUuid = getStringFromConfigFile(context, KEY_CONFIG_PRINTER_UUID)
+        if (configUuid != null) {
```
Comment (yetamrra) [inline app/src/main/java/com/google/virtualprinter/utils/PreferenceUtils.kt:86]: Should this also use `isNullOrEmpty` to avoid the empty config file case?

**Review by yetamrra — APPROVED** [review]
LGTM with one nit.

File: app/src/main/java/com/google/virtualprinter/utils/PreferenceUtils.kt (hunk 1 above)
Comment (nmuggli) [reply app/src/main/java/com/google/virtualprinter/utils/PreferenceUtils.kt:86]: `getStringFromConfigFile` already checks for an empty string, in which case it returns null.  So I think a null check here is sufficient.
